"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0, and further adapted
"""

from jeepney.wrappers import MessageGenerator, new_method_call


class Service(MessageGenerator):
    interface = "org.freedesktop.systemd1.Service"

    def __init__(
            self,
            service: str,
            object_path_base: str = "/org/freedesktop/systemd1/unit",
            bus_name: str = "org.freedesktop.systemd1",
    ):
        object_path = f"{object_path_base}/{service}_2eservice"
        super().__init__(object_path=object_path, bus_name=bus_name)

    def BindMount(self, source, destination, read_only, mkdir):
        return new_method_call(
            self, "BindMount", "ssbb", (source, destination, read_only, mkdir)
        )

    def MountImage(self, source, destination, read_only, mkdir, options):
        return new_method_call(
            self,
            "MountImage",
            "ssbba(ss)",
            (source, destination, read_only, mkdir, options),
        )

    def DumpFileDescriptorStore(self):
        return new_method_call(self, "DumpFileDescriptorStore")

    def GetProcesses(self):
        return new_method_call(self, "GetProcesses")

    def AttachProcesses(self, subcgroup, pids):
        return new_method_call(self, "AttachProcesses", "sau", (subcgroup, pids))


class Unit(MessageGenerator):
    interface = "org.freedesktop.systemd1.Unit"

    def __init__(
            self,
            service: str,
            object_path_base: str = "/org/freedesktop/systemd1/unit",
            bus_name: str = "org.freedesktop.systemd1",
    ):
        object_path = f"{object_path_base}/{service}_2eservice"
        super().__init__(object_path=object_path, bus_name=bus_name)

    def Start(self, mode):
        return new_method_call(self, "Start", "s", (mode,))

    def Stop(self, mode):
        return new_method_call(self, "Stop", "s", (mode,))

    def Reload(self, mode):
        return new_method_call(self, "Reload", "s", (mode,))

    def Restart(self, mode):
        return new_method_call(self, "Restart", "s", (mode,))

    def TryRestart(self, mode):
        return new_method_call(self, "TryRestart", "s", (mode,))

    def ReloadOrRestart(self, mode):
        return new_method_call(self, "ReloadOrRestart", "s", (mode,))

    def ReloadOrTryRestart(self, mode):
        return new_method_call(self, "ReloadOrTryRestart", "s", (mode,))

    def EnqueueJob(self, job_type, job_mode):
        return new_method_call(self, "EnqueueJob", "ss", (job_type, job_mode))

    def Kill(self, whom, signal):
        return new_method_call(self, "Kill", "si", (whom, signal))

    def QueueSignal(self, whom, signal, value):
        return new_method_call(self, "QueueSignal", "sii", (whom, signal, value))

    def ResetFailed(self):
        return new_method_call(self, "ResetFailed")

    def SetProperties(self, runtime, properties):
        return new_method_call(self, "SetProperties", "ba(sv)", (runtime, properties))

    def Ref(self):
        return new_method_call(self, "Ref")

    def Unref(self):
        return new_method_call(self, "Unref")

    def Clean(self, mask):
        return new_method_call(self, "Clean", "as", (mask,))

    def Freeze(self):
        return new_method_call(self, "Freeze")

    def Thaw(self):
        return new_method_call(self, "Thaw")


class UnitProperties(MessageGenerator):
    interface = "org.freedesktop.DBus.Properties"

    def __init__(
            self,
            service: str,
            object_path_base: str = "/org/freedesktop/systemd1/unit",
            bus_name: str = "org.freedesktop.systemd1",
    ):
        object_path = f"{object_path_base}/{service}_2eservice"
        super().__init__(object_path=object_path, bus_name=bus_name)

    def Get(self, iface_name: str, property_name: str):
        return new_method_call(
            self, "Get", "ss", (f"{self.bus_name}.{iface_name}", property_name)
        )


class Manager(MessageGenerator):
    interface = "org.freedesktop.systemd1.Manager"

    def __init__(
            self,
            object_path="/org/freedesktop/systemd1",
            bus_name="org.freedesktop.systemd1",
    ):
        super().__init__(object_path=object_path, bus_name=bus_name)

    def GetUnit(self, name):
        return new_method_call(self, "GetUnit", "s", (name,))

    def GetUnitByPID(self, pid):
        return new_method_call(self, "GetUnitByPID", "u", (pid,))

    def GetUnitByInvocationID(self, invocation_id):
        return new_method_call(self, "GetUnitByInvocationID", "ay", (invocation_id,))

    def GetUnitByControlGroup(self, cgroup):
        return new_method_call(self, "GetUnitByControlGroup", "s", (cgroup,))

    def GetUnitByPIDFD(self, pidfd):
        return new_method_call(self, "GetUnitByPIDFD", "h", (pidfd,))

    def LoadUnit(self, name):
        return new_method_call(self, "LoadUnit", "s", (name,))

    def StartUnit(self, name, mode):
        return new_method_call(self, "StartUnit", "ss", (name, mode))

    def StartUnitWithFlags(self, name, mode, flags):
        return new_method_call(self, "StartUnitWithFlags", "sst", (name, mode, flags))

    def StartUnitReplace(self, old_unit, new_unit, mode):
        return new_method_call(
            self, "StartUnitReplace", "sss", (old_unit, new_unit, mode)
        )

    def StopUnit(self, name, mode):
        return new_method_call(self, "StopUnit", "ss", (name, mode))

    def ReloadUnit(self, name, mode):
        return new_method_call(self, "ReloadUnit", "ss", (name, mode))

    def RestartUnit(self, name, mode):
        return new_method_call(self, "RestartUnit", "ss", (name, mode))

    def TryRestartUnit(self, name, mode):
        return new_method_call(self, "TryRestartUnit", "ss", (name, mode))

    def ReloadOrRestartUnit(self, name, mode):
        return new_method_call(self, "ReloadOrRestartUnit", "ss", (name, mode))

    def ReloadOrTryRestartUnit(self, name, mode):
        return new_method_call(self, "ReloadOrTryRestartUnit", "ss", (name, mode))

    def EnqueueUnitJob(self, name, job_type, job_mode):
        return new_method_call(
            self, "EnqueueUnitJob", "sss", (name, job_type, job_mode)
        )

    def KillUnit(self, name, whom, signal):
        return new_method_call(self, "KillUnit", "ssi", (name, whom, signal))

    def QueueSignalUnit(self, name, whom, signal, value):
        return new_method_call(
            self, "QueueSignalUnit", "ssii", (name, whom, signal, value)
        )

    def CleanUnit(self, name, mask):
        return new_method_call(self, "CleanUnit", "sas", (name, mask))

    def FreezeUnit(self, name):
        return new_method_call(self, "FreezeUnit", "s", (name,))

    def ThawUnit(self, name):
        return new_method_call(self, "ThawUnit", "s", (name,))

    def ResetFailedUnit(self, name):
        return new_method_call(self, "ResetFailedUnit", "s", (name,))

    def SetUnitProperties(self, name, runtime, properties):
        return new_method_call(
            self, "SetUnitProperties", "sba(sv)", (name, runtime, properties)
        )

    def BindMountUnit(self, name, source, destination, read_only, mkdir):
        return new_method_call(
            self,
            "BindMountUnit",
            "sssbb",
            (name, source, destination, read_only, mkdir),
        )

    def MountImageUnit(self, name, source, destination, read_only, mkdir, options):
        return new_method_call(
            self,
            "MountImageUnit",
            "sssbba(ss)",
            (name, source, destination, read_only, mkdir, options),
        )

    def RefUnit(self, name):
        return new_method_call(self, "RefUnit", "s", (name,))

    def UnrefUnit(self, name):
        return new_method_call(self, "UnrefUnit", "s", (name,))

    def StartTransientUnit(self, name, mode, properties, aux):
        return new_method_call(
            self,
            "StartTransientUnit",
            "ssa(sv)a(sa(sv))",
            (name, mode, properties, aux),
        )

    def GetUnitProcesses(self, name):
        return new_method_call(self, "GetUnitProcesses", "s", (name,))

    def AttachProcessesToUnit(self, unit_name, subcgroup, pids):
        return new_method_call(
            self, "AttachProcessesToUnit", "ssau", (unit_name, subcgroup, pids)
        )

    def AbandonScope(self, name):
        return new_method_call(self, "AbandonScope", "s", (name,))

    def GetJob(self, id):
        return new_method_call(self, "GetJob", "u", (id,))

    def GetJobAfter(self, id):
        return new_method_call(self, "GetJobAfter", "u", (id,))

    def GetJobBefore(self, id):
        return new_method_call(self, "GetJobBefore", "u", (id,))

    def CancelJob(self, id):
        return new_method_call(self, "CancelJob", "u", (id,))

    def ClearJobs(self):
        return new_method_call(self, "ClearJobs")

    def ResetFailed(self):
        return new_method_call(self, "ResetFailed")

    def SetShowStatus(self, mode):
        return new_method_call(self, "SetShowStatus", "s", (mode,))

    def ListUnits(self):
        return new_method_call(self, "ListUnits")

    def ListUnitsFiltered(self, states):
        return new_method_call(self, "ListUnitsFiltered", "as", (states,))

    def ListUnitsByPatterns(self, states, patterns):
        return new_method_call(self, "ListUnitsByPatterns", "asas", (states, patterns))

    def ListUnitsByNames(self, names):
        return new_method_call(self, "ListUnitsByNames", "as", (names,))

    def ListJobs(self):
        return new_method_call(self, "ListJobs")

    def Subscribe(self):
        return new_method_call(self, "Subscribe")

    def Unsubscribe(self):
        return new_method_call(self, "Unsubscribe")

    def Dump(self):
        return new_method_call(self, "Dump")

    def DumpUnitsMatchingPatterns(self, patterns):
        return new_method_call(self, "DumpUnitsMatchingPatterns", "as", (patterns,))

    def DumpByFileDescriptor(self):
        return new_method_call(self, "DumpByFileDescriptor")

    def DumpUnitsMatchingPatternsByFileDescriptor(self, patterns):
        return new_method_call(
            self, "DumpUnitsMatchingPatternsByFileDescriptor", "as", (patterns,)
        )

    def Reload(self):
        return new_method_call(self, "Reload")

    def Reexecute(self):
        return new_method_call(self, "Reexecute")

    def Exit(self):
        return new_method_call(self, "Exit")

    def Reboot(self):
        return new_method_call(self, "Reboot")

    def SoftReboot(self, new_root):
        return new_method_call(self, "SoftReboot", "s", (new_root,))

    def PowerOff(self):
        return new_method_call(self, "PowerOff")

    def Halt(self):
        return new_method_call(self, "Halt")

    def KExec(self):
        return new_method_call(self, "KExec")

    def SwitchRoot(self, new_root, init):
        return new_method_call(self, "SwitchRoot", "ss", (new_root, init))

    def SetEnvironment(self, assignments):
        return new_method_call(self, "SetEnvironment", "as", (assignments,))

    def UnsetEnvironment(self, names):
        return new_method_call(self, "UnsetEnvironment", "as", (names,))

    def UnsetAndSetEnvironment(self, names, assignments):
        return new_method_call(
            self, "UnsetAndSetEnvironment", "asas", (names, assignments)
        )

    def EnqueueMarkedJobs(self):
        return new_method_call(self, "EnqueueMarkedJobs")

    def ListUnitFiles(self):
        return new_method_call(self, "ListUnitFiles")

    def ListUnitFilesByPatterns(self, states, patterns):
        return new_method_call(
            self, "ListUnitFilesByPatterns", "asas", (states, patterns)
        )

    def GetUnitFileState(self, file):
        return new_method_call(self, "GetUnitFileState", "s", (file,))

    def EnableUnitFiles(self, files, runtime, force):
        return new_method_call(self, "EnableUnitFiles", "asbb", (files, runtime, force))

    def DisableUnitFiles(self, files, runtime):
        return new_method_call(self, "DisableUnitFiles", "asb", (files, runtime))

    def EnableUnitFilesWithFlags(self, files, flags):
        return new_method_call(self, "EnableUnitFilesWithFlags", "ast", (files, flags))

    def DisableUnitFilesWithFlags(self, files, flags):
        return new_method_call(self, "DisableUnitFilesWithFlags", "ast", (files, flags))

    def DisableUnitFilesWithFlagsAndInstallInfo(self, files, flags):
        return new_method_call(
            self, "DisableUnitFilesWithFlagsAndInstallInfo", "ast", (files, flags)
        )

    def ReenableUnitFiles(self, files, runtime, force):
        return new_method_call(
            self, "ReenableUnitFiles", "asbb", (files, runtime, force)
        )

    def LinkUnitFiles(self, files, runtime, force):
        return new_method_call(self, "LinkUnitFiles", "asbb", (files, runtime, force))

    def PresetUnitFiles(self, files, runtime, force):
        return new_method_call(self, "PresetUnitFiles", "asbb", (files, runtime, force))

    def PresetUnitFilesWithMode(self, files, mode, runtime, force):
        return new_method_call(
            self, "PresetUnitFilesWithMode", "assbb", (files, mode, runtime, force)
        )

    def MaskUnitFiles(self, files, runtime, force):
        return new_method_call(self, "MaskUnitFiles", "asbb", (files, runtime, force))

    def UnmaskUnitFiles(self, files, runtime):
        return new_method_call(self, "UnmaskUnitFiles", "asb", (files, runtime))

    def RevertUnitFiles(self, files):
        return new_method_call(self, "RevertUnitFiles", "as", (files,))

    def SetDefaultTarget(self, name, force):
        return new_method_call(self, "SetDefaultTarget", "sb", (name, force))

    def GetDefaultTarget(self):
        return new_method_call(self, "GetDefaultTarget")

    def PresetAllUnitFiles(self, mode, runtime, force):
        return new_method_call(
            self, "PresetAllUnitFiles", "sbb", (mode, runtime, force)
        )

    def AddDependencyUnitFiles(self, files, target, type, runtime, force):
        return new_method_call(
            self,
            "AddDependencyUnitFiles",
            "asssbb",
            (files, target, type, runtime, force),
        )

    def GetUnitFileLinks(self, name, runtime):
        return new_method_call(self, "GetUnitFileLinks", "sb", (name, runtime))

    def SetExitCode(self, number):
        return new_method_call(self, "SetExitCode", "y", (number,))

    def LookupDynamicUserByName(self, name):
        return new_method_call(self, "LookupDynamicUserByName", "s", (name,))

    def LookupDynamicUserByUID(self, uid):
        return new_method_call(self, "LookupDynamicUserByUID", "u", (uid,))

    def GetDynamicUsers(self):
        return new_method_call(self, "GetDynamicUsers")

    def DumpUnitFileDescriptorStore(self, name):
        return new_method_call(self, "DumpUnitFileDescriptorStore", "s", (name,))
